# -*- mode: python -*-

def common(ctx):
    ctx.load("compiler_c")
    ctx.load("core", tooldir="ext/waf-sfiera")

def options(opt):
    common(opt)
    opt.add_option(
            "--with-ogg", action="store", default="auto", choices=["system", "bundled", "auto"],
            metavar="system|bundled|auto",
            help="select between system-provided and bundled libogg [default: 'auto']")

def configure(cnf):
    common(cnf)
    if cnf.options.with_ogg == "system":
        cnf.check_cc(lib="ogg", uselib_store="ogg/libogg")
        cnf.env.bundled_ogg = False
    elif cnf.options.with_ogg == "bundled":
        cnf.env.bundled_ogg = True
    else:
        cnf.check_cc(lib="ogg", uselib_store="ogg/libogg", mandatory=False)
        cnf.env.bundled_ogg = "LIB_ogg/libogg" not in cnf.env

def build(bld):
    common(bld)

    if bld.env.bundled_ogg:
        bld.stlib(
            target="ogg/libogg",
            features="universal",
            source=[
                "libogg-1.3.0/src/bitwise.c",
                "libogg-1.3.0/src/framing.c",
            ],
            includes="libogg-1.3.0/include",
            export_includes="libogg-1.3.0/include",
        )

        bld.platform(
            target="ogg/libogg",
            platform="darwin",
            includes="darwin",
            export_includes="darwin",
        )
