# -*- mode: python -*-

WARNINGS = ["-Wno-format-security", "-Wno-tautological-compare"]

def common(ctx):
    ctx.load("compiler_c")
    ctx.load("core", tooldir="ext/waf-sfiera")

def options(opt):
    common(opt)
    opt.add_option(
            "--with-mad", action="store", default="auto", choices=["system", "bundled", "auto"],
            metavar="system|bundled|auto",
            help="select between system-provided and bundled libmad [default: 'auto']")

def configure(cnf):
    common(cnf)

    if cnf.options.with_mad == "system":
        cnf.check_cc(lib="mad", uselib_store="mad/libmad")
        cnf.env.bundled_mad = False
    elif cnf.options.with_mad == "bundled":
        cnf.env.bundled_mad = True
    else:
        cnf.check_cc(lib="mad", uselib_store="mad/libmad", mandatory=False)
        cnf.env.bundled_mad = "LIB_mad/libmad" not in cnf.env
    assert not cnf.env.bundled_mad  # don't support bundled yet.

def build(bld):
    common(bld)
